spring:
  application:
    name: spring-dotfile-manager
  shell:
    interactive:
      enabled: false

spring-dotfile-manager:
  config:
    path: "{HOME}/.config/spring-dotfile-manager/config.yaml"
