spring:
  application:
    name: spring-dotfile-manager
  shell:
    interactive:
      enabled: false
    command:
      history:
        enabled: false
      clear:
        enabled: false
      script:
        enabled: false
  main:
    banner-mode: "off"

spring-dotfile-manager:
  config:
    path: "{HOME}/.config/spring-dotfile-manager/config.yaml"
    default-repo-path: "{HOME}/dotfiles"
  dotfile-glob-pattern: "**/.dotfiles"
