spring:
  application:
    name: spring-dotfile-manager
  main:
    banner-mode: "off"
    log-startup-info: false

spring-dotfile-manager:
  config:
    path: 
      linux: "{HOME}/.config/spring-dotfile-manager/config.yaml"
      darwin: "{HOME}/.config/spring-dotfile-manager/config.yaml"
      win32: "{HOME}/AppData/Local/spring-dotfile-manager/config.yaml"
    default-repo-path: "{HOME}/dotfiles"
  dotfile-glob-pattern: "**/.dotfiles"

logging:
  pattern:
    console: "%msg%n"
  level:
    org.springframework: warn
